### ISSUE TITLE
bqm.resize should not return a value

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/dimod#1091]
**Description**
(https://github.com/dwavesystems/dimod/blob/220a22ae53a422e04476bfeb5654e8c475120895/dimod/binary/binary_quadratic_model.py#L1600) :

```
return self.data.resize
```
returns a zero when this method is run. Why? 

**Steps To Reproduce**

```
bqm.resize(3)
0
```

**Expected Behavior**
Quietly do its work.

**Environment**
 - OS: WIN10
 - Python version: 3.6

**Additional Context**
I'm in that file now, can I delete the `return` ?

**Comment by arcondello** [comment]
We need to return a value in order to be able to raise an exception. See [error return values](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#error-return-values).

**Comment by JoelPasvolsky** [comment]
What about returning the difference in number of variables between current and previous BQM rather than 0?

**Comment by arcondello** [comment]
Also, to be clear, https://github.com/dwavesystems/dimod/blob/220a22ae53a422e04476bfeb5654e8c475120895/dimod/binary/binary_quadratic_model.py#L1600 does not return the value of zero, it is returning the method to be used. See https://github.com/dwavesystems/dimod/blob/220a22ae53a422e04476bfeb5654e8c475120895/dimod/decorators.py#L406

The value is returned by https://github.com/dwavesystems/dimod/blob/220a22ae53a422e04476bfeb5654e8c475120895/dimod/binary/cybqm/cybqm_template.pyx.pxi#L713 which is a `cpdef` function which is why we need that return value.

**Comment by arcondello** [comment]
> What about returning the difference in number of variables between current and previous BQM rather than 0?

Could just be the size of the resulting BQM (since -1 is what indicates an error). It's a bit redundant since that's the value being passed in but at least would be a bit more meaningful :shrug:

**Comment by arcondello** [comment]
> What about returning the difference in number of variables between current and previous BQM rather than 0?

Changed my mind, your idea is better. We can just error on 0 instead since that should be an uncommon case if we're returning the delta.
