### ISSUE TITLE
Please don't hard-code catch paths

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dimod#1240]
**Description**
Instead of:
```
#include "../Catch2/single_include/catch2/catch.hpp"
```
it should be
```
#include <catch2/catch.hpp>
```
Then makefile should take care of the include path.
If the git submodule is present - it should be used. If not - ``` `pkg-config --cflags catch2` ``` should be used.

And it doesn't make sense to run git from makefiles because in many cases this directory comes from a tarball and it isn't a git repository.

**Comment by arcondello** [comment]
> Then makefile should take care of the include path.

This makes sense to me.

> And it doesn't make sense to run git from makefiles because in many cases this directory comes from a tarball and it isn't a git repository.

In this case - because we include catch2 as a git submodule with a specific commit - I think it makes sense to keep it here. Worth remembering that although this package has some C++ and may some day get more direct C++ use, for now 99% of its users interface with it as a Python package. Keeping the instructions for running the C++ tests simple and in a MakeFile is useful. At some point in the future we could consider a more sophisticated CMake infrastructure.
