### ISSUE TITLE
order of the indices of a quadratic interaction get reversed with respect to initial specification

### ISSUE THREAD

**Issue by pau557** [dwavesystems/dimod#531]
**Description**
A rare case in which the indices (i, j) of a quadratic interaction are returned in the reverse order when accessing the values in bqm.quadratic

**Steps To Reproduce**
```
In [1]: J = {(1, 3): 1, (2, 3): 1}

In [2]: import dimod

In [3]: bqm = dimod.BQM.from_ising({}, J)

In [4]: [key for key in bqm.quadratic.keys()]
Out[4]: [(1, 3), (3, 2)]

```

**Expected Behavior**
```

In [4]: [key for key in bqm.quadratic.keys()]
Out[4]: [(1, 3), (2, 3)]

```

**Environment**
 - OS:  Ubuntu 16.04.5 LTS
 - Python version: Python 3.7.2
 - Dimod version: 0.8.15

**Comment by randomir** [comment]
The reason for this unexpected behavior is that `3` node is inserted into BQM's adjacency dictionary before `2` is, during the first interaction processing. Nodes are added in this order: `1, 3, 2`.

Since dict is ordered in Python 3.6+, iteration over the adjacency dict will yield edges in exactly that order.

**Comment by pau557** [comment]
The issue that I see with this is that I cannot check the value of the (2, 3) edge from `bqm.quadratic` without trying both order permutations

**Comment by randomir** [comment]
But you can. Both directed edges are set:
```
In [12]: bqm.quadratic[(2,3)]                                                                                                                                                                                                                                                             
Out[12]: 1

In [13]: bqm.quadratic[(3,2)]  
Out[12]: 1
```

**Comment by randomir** [comment]
Since we promote the use of views instead of direct adjacency dict access, we might change this behavior -- to never add both directed edges for a single undirected edge, and then handle the look-up in the view. But that would slow down the look-up, and possibly cause problems for numpy-based implementations of BQM.

**Comment by randomir** [comment]
One workaround you might consider if the order is important to you -- is to add linear biases in the desired order. For example:
```
h = {1: 0, 2: 0, 3: 0}
J = {(1, 3): 1, (2, 3): 1}
bqm = dimod.BQM.from_ising(h, J)
```

**Comment by pau557** [comment]
This works for me because my indices are always sorted:
```
J = {tuple(sorted(indices)): val for indices, val in bqm.quadratic.items()}
```
Your workaround sounds safer, but it takes away the pleasure of setting `h = {}` :)

**Comment by randomir** [comment]
Oh, and just to note, if you want the workaround to work in older versions of Python (prior to 3.6), you must use `h = collections.OrderedDict([(1, 0), (2, 0), (3, 0)])`.

**Comment by arcondello** [comment]
We used to have an ordered bqm (see #397). Also worth noting that the new experimental bqms in #533 are ordered.
