### ISSUE TITLE
Initial state parser modifies input states inplace

### ISSUE THREAD

**Issue by randomir** [dwavesystems/dimod#861]
The root cause of https://github.com/dwavesystems/dwave-tabu/issues/86 is the behavior of `Initialized.parse_initial_states`, where `as_samples` is used with `copy=False` default, and then vartype converted in place, modifying the input `initial_states` -- but only partially. Raw sample data is converted, but SampleSet's vartype is not.

https://github.com/dwavesystems/dimod/blob/30272a7e47ec71988413ce8f8339d397ceff8d17/dimod/core/initialized.py#L126-L131

**Comment by hhtong** [comment]
There seems to be a bug in `as_samples` as well, where the `copy` argument is ignored for certain cases (ie. the one mentioned in dwavesystems/dwave-tabu#86)

https://github.com/dwavesystems/dimod/blob/43fa43063067ae81d160d7f0ab2dd5e5f0b7e931/dimod/sampleset.py#L266-L269

It seems like the fix for this issue is to address the `as_samples` bug and then call `as_samples` with `copy=True`.
