### ISSUE TITLE
Support powers of two symbolically

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#864]
Something like
```
class BinaryQuadraticModel:
    ....

    def __pow__(self, n: int):
        if n != 2:
            raise ValueError("n must be 2")
        if not self.is_linear():
            raise ValueError("must be linear")
        return self * self
```

**Pro:**
- Makes for slightly nicer syntax, e.g `(x + y + z)**2` rather than `(x+y+z)*(x+y*z)`
    - secondary benefit is fewer new objects created in the former rather than the latter 

**Con:**
- Only supports a very restrictive circumstance: squaring linear models (see https://github.com/dwavesystems/dimod/pull/790#discussion_r568838430 )
- Makes it slightly easier to do inefficient things with `ConstrainedQuadraticModel` like `cqm.add_constraint((x + y + z)**2 == 4)` rather than `cqm.add_constraint(x+y+z==2)`

**Comment by hsadeghidw** [comment]
_Makes it slightly easier to do inefficient things with ConstrainedQuadraticModel like cqm.add_constraint((x + y + z)**2 == 4) rather than cqm.add_constraint(x+y+z==2)_

That is a good point. I am not experienced with how users make mistakes like that. I think having `**2` is nice, and it's your call if the users may use it inefficiently. 

I think that restrictive behavior is okay. We can always come back to this and make it less restrictive.
